version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-panchesco13/banknote-classifier}:${TAG:-latest}
    ports:
      - "8080:8080"
    # environment:
    #   - MONGODB_URI=mongodb://mongodb:27017
    #   - MONGODB_DB_NAME=mlops_db
    #   - MONGODB_USER=root
    #   - MONGODB_PASSWORD=password
    #   - MONGODB_AUTH_SOURCE=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    #  environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=password