name: Test and Verify CD

on:
  repository_dispatch:
    types: 
      - cd

env:
  DOCKER_IMAGE: panchesco13/banknote-classifier

jobs:
  cd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull the latest image
      run: |
        docker pull ${DOCKER_IMAGE}:latest

    - name: Start the services using docker compose
      run: |
        docker compose up -d

    - name: Wait for services to start
      run: |
        sleep 30  # Даем время на инициализацию сервисов

    - name: Check containers
      run: |
        docker compose ps

    - name: Check logs
      run: |
        docker compose logs app

    - name: Run functional tests
      run: |
        # Устанавливаем зависимости для тестов
        pip install -r requirements.txt
        
        # Запускаем функциональные тесты
        python -m pytest tests/test_functional.py -v

    - name: Cleanup
      run: |
        docker compose down
        docker system prune -f