name: cd

on:
  repository_dispatch:
    types: [cd-trigger]
    
env:
  DOCKER_IMAGE: panchesco13/banknote-classifier
  TAG: ${{ github.event.client_payload.sha || github.sha }}

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull containers
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:app-${{ env.TAG }}
          docker pull ${{ env.DOCKER_IMAGE }}:vault-${{ env.TAG }}
          docker pull ${{ env.DOCKER_IMAGE }}:mongodb-${{ env.TAG }}

      - name: Start containers
        run: |
          docker-compose -f docker-compose.test.yml up -d
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

      - name: Wait for services
        run: |
          sleep 30  # Wait for services to start
          docker-compose -f docker-compose.test.yml ps

      - name: Run functional tests
        run: |
          docker-compose -f docker-compose.test.yml exec app python -m pytest tests/functional/ -v

      - name: Run integration tests
        run: |
          docker-compose -f docker-compose.test.yml exec app python -m pytest tests/integration/ -v

      - name: Check test results
        if: always()
        run: |
          docker-compose -f docker-compose.test.yml logs app
          docker-compose -f docker-compose.test.yml logs vault
          docker-compose -f docker-compose.test.yml logs mongodb

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f docker-compose.test.yml down -v