name: ci

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

env:
  DOCKER_IMAGE: panchesco13/banknote-classifier
  TAG: ${{ github.sha }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  TAG: ${{ secrets.TAG }}
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
  MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker compose build
          docker push ${DOCKER_IMAGE}:${{ github.sha }}

      - name: Trigger CD pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: maxim-panchuk/mlops_3
          event-type: cd-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
